pipeline {
    agent any

    stages {

        stage('Build') {
            steps {
                script {
                    echo 'Building Docker image...'
                    docker.build('pathnex-web-app')
                }
            }
        }

        stage('Test') {
            steps {
                echo 'Running tests...'
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                script {
                    sh 'kubectl apply -f kubernetes/deployment.yaml'
                }
            }
        }
    }
}
