pipeline {
    agent any

    environment {
        IMAGE_NAME = "pathnex-web-app"
    }

    stages {

        stage('Build') {
            steps {
                script {
                    docker.build("${IMAGE_NAME}")
                }
            }
        }

        stage('Test') {
            steps {
                echo "Running tests..."
            }
        }

        stage('Deploy') {
            steps {
                sh 'kubectl apply -f kubernetes/deployment.yaml'
                sh 'kubectl rollout status deployment/pathnex-web-app'
            }
        }
    }
}
