apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: pathnex-vpc-policy
spec:
  podSelector:
    matchLabels:
      app: pathnex-app
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: pathnex-db