pipeline {
    agent any

    stages {

        stage('Deploy to US East Cluster') {
            steps {
                sh 'kubectl --context=us-east-cluster apply -f kubernetes/deployment.yaml'
            }
        }

        stage('Deploy to US West Cluster') {
            steps {
                sh 'kubectl --context=us-west-cluster apply -f kubernetes/deployment.yaml'
            }
        }

    }
}
