pipeline {
    agent any

    stages {

        stage('Backup') {
            steps {
                sh 'tar -czvf /tmp/jenkins-backup.tar.gz ${WORKSPACE}'
            }
        }

        stage('Restore') {
            steps {
                sh 'tar -xzvf /tmp/jenkins-backup.tar.gz -C ${WORKSPACE}'
            }
        }

    }
}
