pipeline {
    agent any

    stages {

        stage('Build') {
            steps {
                script {
                    docker.build("pathnex-web-app")
                }
            }
        }

        stage('Test') {
            steps {
                echo 'Running Tests...'
            }
        }

        stage('Deploy') {
            steps {
                script {
                    if (env.CLUSTER == "us-east") {
                        sh 'kubectl --context=us-east apply -f kubernetes/deployment.yaml'
                    } else {
                        sh 'kubectl --context=us-west apply -f kubernetes/deployment.yaml'
                    }
                }
            }
        }
    }
}
